module.exports = [
  {
    name: 'Nay Yaung Lin Lakk',
    description: 'Student, MERN Stack, A Nunchaku Player, started learning web technologies at age 13 :)',
    url: 'https://nayyaung9.github.io',
    github: 'nayyaung9',
    emoji: '😎',
    computer: 'linux',
    phone: 'android',
    tags: [
      'Developer',
      'Full Stack',
      'Node',
      'React',
      'React Native',
      'Next',
      'Gatsby',
      'JavaScript',
      'Redux',
      'Mongo',
    ],
  },
  {
    name: 'Min Thu Kyaw',
    description: 'Student, Biker',
    url: 'https://thukyaw11.github.io',
    github: 'thukyaw11',
    emoji: '🔥',
    computer: 'linux',
    phone: 'android',
    tags: [
      'Developer',
      'Full Stack',
      'Vue',
      'Vuex',
      'Nuxt',
      'Php',
      'JavaScript',
      'Laravel',
      'mysql',
      'c++'
    ],
  },
  {
    name: 'Shoon Lei Naing',
    description: 'Student from UIT',
    url: '',
    github: 'ShoonLeiNaing',
    emoji: '🙇‍',
    computer: 'windows',
    phone: 'iphone',
    tags: [
      'Developer',
      'back-end',
      'Python',
      'C++',
      'JavaScript'

    ],
  },
  {
    name: 'Pyae Sone Khant',
    description: 'Student',
    url: 'https://zeroboycoder.github.io/',
    github: 'zeroboycoder',
    emoji: '🤠',
    computer: 'linux',
    phone: 'android',
    tags: [
      'Developer',
      'Full Stack',
      'JavaScript',
      'Node',
      'Express',
      'React',
      'Mongo',
      'mysql'
    ],
  },
  {
    name: 'Nine_Ball',
    description: 'Software Engineer',
    url: 'https://github.com/Nine-Ball9',
    github: 'Nine-Ball9',
    emoji: '👩‍💻',
    computer: 'mac',
    phone: 'android',
    tags: [
      'Developer',
      'Frontend',
      'React',
      'React Native',
      'Laravel',
      'JavaScript',
      'Python',
    ],
  },
];

