module.exports = [
  {
    name: 'Nay Yaung Lin Lakk',
    description: 'Student, MERN Stack, A Nunchaku Player, started learning web technologies at age 13 :)',
    url: 'https://nayyaung9.github.io',
    github: 'nayyaung9',
    emoji: '😎',
    computer: 'linux',
    phone: 'android',
    tags: [
      'Developer',
      'Full Stack',
      'Node',
      'React',
      'React Native',
      'Next',
      'Gatsby',
      'JavaScript',
      'Redux',
      'Mongo',
    ],
  },
  {
    name: 'Min Thu Kyaw',
    description: 'Student, Biker',
    url: 'https://thukyaw11.github.io',
    github: 'thukyaw11',
    emoji: '🔥',
    computer: 'linux',
    phone: 'android',
    tags: [
      'Developer',
      'Full Stack',
      'Vue',
      'Vuex',
      'Nuxt',
      'Php',
      'JavaScript',
      'Laravel',
      'mysql',
      'C++'
    ],
  },
  {
    name: 'Shoon Lei Naing',
    description: 'Student from UIT',
    url: '',
    github: 'ShoonLeiNaing',
    emoji: '🙇‍',
    computer: 'windows',
    phone: 'iphone',
    tags: [
      'Developer',
      'back-end',
      'Python',
      'C++',
      'JavaScript'

    ],
  },
  {
    name: 'Pyae Sone Khant',
    description: 'Student',
    url: 'https://zeroboycoder.github.io/',
    github: 'zeroboycoder',
    emoji: '🤠',
    computer: 'linux',
    phone: 'android',
    tags: [
      'Developer',
      'Full Stack',
      'JavaScript',
      'Node',
      'Express',
      'React',
      'Mongo',
      'mysql'
    ],
  },
  {
    name: 'Nine_Ball',
    description: 'Software Engineer',
    url: 'https://github.com/Nine-Ball9',
    github: 'Nine-Ball9',
    emoji: '👩‍💻',
    computer: 'apple',
    phone: 'android',
    tags: [
      'Developer',
      'Frontend',
      'React',
      'React Native',
      'Laravel',
      'JavaScript',
      'Python',
    ],
  },
  {
    name: 'PosaLusa24',
    description: 'UIT Student, Hobbyist Dev',
    url: 'https://posalusa24.github.io',
    github: 'PosaLusa24',
    emoji: '🥺',
    computer: 'linux',
    phone: 'android',
    tags: [
      'Backend',
      'Linux Kernel',
      'C++',
      'Python',
      'Node',
      'Weeb',
    ],
  },
  {
    name: 'Min Kaung Kyaw',
    description: 'Student',
    url: 'https://github.com/mwebeducation',
    github: 'mwebeducation',
    emoji: '',
    computer: 'linux',
    phone: 'android',
    tags: [
      'Developer',
      'MernStack',
      'React',
      'React Native',
      'Flutter',
      'JavaScript',
      'Python',
    ],
  },
  {
        name: "Hein Thanth",
        description: "Full stack Web Developer",
        url: "https://heinthanth.com",
        github: "heinthanth",
        emoji: "😺",
        computer: "linux",
        phone: "android",
        tags: [
            "Full Stack",
            "Developer",
            "PHP",
            "Laravel",
            "JavaScript",
            "Node",
            "React",
            "Mongo",
            "MySQL",
            "C++",
            "Python",
        ],
    },
    {
        name: "Htoo Aung Lynn(Chester)",
        description: "Student from MIIT",
        url: "https://github.com/halchester",
        github: "halchester",
        emoji: "😴",
        computer: "apple",
        phone: "iphone",
        tags: [
            "Frontend",
            "HTML",
            "CSS",
            "Javascript",
            "Python",
            "C",
            "Machine Learning",
            "PostgreSQL",
            "SwiftUI",
        ],
    },
    {
      name: "La Wun Nannda",
      description: "student from YTU",
      url: "https://github.com/lawun330",
      github: "lawun330",
      emoji: "😗",
      computer: "windows",
      phone: "android",
      tags: [
            "C++",
            "Python",
            "Machine Learning",
            "OpenCV",
            "Arduino",
            "Tensor Flow",
            "Octave",
        ],
    },
{
      name: "PhoneMyat Pyae Sone",
      description: "student",
      url: "https://github.com/Gr3y-PhoNiex",
      github: "Gr3y-PhoNiex",
      emoji: "😎",
      computer: "linux",
      phone: "android",
      tags: [
            "HTML",
            "CSS",
            "JavaScript",
            "Python",
        ],
    },
];

