module.exports = [
  {
    name: 'Nay Yaung Lin Lakk',
    description: 'Fullstack Dev, Student',
    url: 'https://nayyaung9.github.io',
    twitter: '@LakkNay',
    emoji: '🎿',
    country: '🇫🇷',
    computer: 'dell',
    phone: 'redmi',
    tags: [
      'Developer',
      'Full Stack',
      'Web',
      'React',
      'Next',
      'Gatsby',
      'JavaScript',
      'Redux',
      'Vuetify',
    ],
  },
  {
    name: 'Nay Yaung Lin Lakk',
    description: 'Fullstack Dev, Student',
    url: 'https://nayyaung9.github.io',
    twitter: '@LakkNay',
    emoji: '🎿',
    country: '🇫🇷',
    computer: 'dell',
    phone: 'redmi',
    tags: [
      'Developer',
      'Full Stack',
      'Web',
      'React',
      'Next',
      'Gatsby',
      'JavaScript',
      'Redux',
      'Vuetify',
    ],
  },
  {
    name: 'Nay Yaung Lin Lakk',
    description: 'Fullstack Dev, Student',
    url: 'https://nayyaung9.github.io',
    twitter: '@LakkNay',
    emoji: '🎿',
    country: '🇫🇷',
    computer: 'dell',
    phone: 'redmi',
    tags: [
      'Developer',
      'Full Stack',
      'Web',
      'React',
      'Next',
      'Gatsby',
      'JavaScript',
      'Redux',
      'Vuetify',
    ],
  },
  {
    name: 'Nay Yaung Lin Lakk',
    description: 'Fullstack Dev, Student',
    url: 'https://nayyaung9.github.io',
    twitter: '@LakkNay',
    emoji: '🎿',
    country: '🇫🇷',
    computer: 'dell',
    phone: 'redmi',
    tags: [
      'Developer',
      'Full Stack',
      'Web',
      'React',
      'Next',
      'Gatsby',
      'JavaScript',
      'Redux',
      'Vuetify',
    ],
  },
];